# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'app' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for app

end

target 'iosApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosApp

  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Database'

  target 'iosAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
